package game;

public enum Status {

	DIRT,GRASS,OLD_TREE,
	YOUNG_TREE, PROEGG,
	VELOEGG, CORPSE,BABY,
	ADULT,PLAYER,SHOP,
	PASSABLE, WATER, REEDS
	, FISH, PLEEGG, EGG, CARNIVORE,
	PROTOCERATOPS, CARNIVOREFOOD, PLEBABY, 
	PLESIOSAURS, PTERANODONS
	


}
